### ISSUE TITLE
Getting a TypeError crash

### ISSUE THREAD

**Issue by doginthehat** [SteffeyDev/react-native-popover-view#10]
Hi, 

I keep running in the same crash, takes a few seconds to popup but it always does.

Can't quite work out what's causing it. 

I'm running it with Expo (v28).

![simulator screen shot - iphone 8 - 2018-08-08 at 13 17 43](https://user-images.githubusercontent.com/843366/43815263-1388efae-9b0e-11e8-9438-4db2543a9687.png)

Not sure what else to provide. Let me know what could help?

Ben

**Comment by doginthehat** [comment]
Seems to be triggered by this (according to the debugger)

<img width="626" alt="screen shot 2018-08-08 at 13 42 42" src="https://user-images.githubusercontent.com/843366/43815979-aa8b9f5c-9b11-11e8-8d38-24abc032c175.png">

**Comment by SteffeyDev** [comment]
Thanks for doing all the debugging work! I'll make that change real fast and we'll see if it fixes the issue.

**Comment by doginthehat** [comment]
@SteffeyDev Thanks for your quick reply too!

**Comment by SteffeyDev** [comment]
@doginthehat Ok, I just published version 1.0.1 on NPM which includes the fix, let me know if it works for you!

**Comment by doginthehat** [comment]
That's quick! Trying now.

**Comment by doginthehat** [comment]
Smashed it, all done.

**Comment by doginthehat** [comment]
There should be an award for fastest resolved github issue 🏆

**Comment by SteffeyDev** [comment]
Awesome!
