### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by rlugge** [SteffeyDev/react-native-popover-view#11]
So I just started trying to use this, and immediately got an error:

```Unable to resolve ../../react-navigation/src/navigators/createKeyboardAwareNavigator" from ".//node_modules/react-native-popover-view/src/PopoverStackNavigator.js`: The module `../../react-navigation/src/navigators/createKeyboardAwareNavigator` could not be found"```

Not sure what I did wrong here.

**Comment by SteffeyDev** [comment]
What version of react-navigation are you using?

**Comment by rlugge** [comment]
Looks like 1.5.12.

**Comment by SteffeyDev** [comment]
Ok, I officially only support version 2, and unfortunately don’t have time to do backward comparability right now with older versions. Can you upgrade to the latest version of react-navigation? I don’t know if they made any breaking changes or not.

**Comment by rlugge** [comment]
Ah.  My understanding is they made a number of breaking changes.  Sorry to
have bothered you, didn't catch the dependency issue.

**Comment by SteffeyDev** [comment]
Ok, do you have an interest in using the popover independently of react navigation? I can provide instructions to decouple it, though as long as my library detects react-navigation it will try to link it.

**Comment by rlugge** [comment]
Nah, thanks but I found a work-around with a different UI option.  I'm just
shocked this isn't a core react-native feature.

**Comment by SteffeyDev** [comment]
Ok glad you found a solution!  One of the things about react native is that there is no navigation components built in, though I suppose you can count react-navigation because it is the recommended UI library. I’d love to merge this into react-navigation someday.

Anyways, is it ok if I close the issue?
