### ISSUE TITLE
Shadow not appearing for arrow

### ISSUE THREAD

**Issue by Manoj002** [SteffeyDev/react-native-popover-view#116]
**Describe the bug**
Hello, im trying to render the popover as rn-modal and using popoverStyle and arrowStyle to provide style.

Issue 1:
Shadow is working for popover in android and ios, but shadow is not appearing for arrow in android and ios

Android:
![image](https://user-images.githubusercontent.com/10413690/129550473-b20965fe-6174-4186-815e-1710b34f57b5.png)

iOS:
![image](https://user-images.githubusercontent.com/10413690/129556212-01409389-8220-4d2a-9eda-0d467eac4032.png)

Issue 2: 
the arrow seems below the modal in android when placement is other than bottom

with placement = top

![image](https://user-images.githubusercontent.com/10413690/129556325-a5846446-2cba-496f-86b5-a6918feba25c.png)

**Device/Setup Info:**
 - Device: [iPhone 11] and Android Pixel 4
 - OS: [iOS 13.0]
 - `react-native` version: [0.63.2]
- `react-native-popover-view` version: [4.0.1]

**Screenshots**
If there is a visual issue, add screenshots or a video so that I can see what is going on.

**Debug Output**
Pass the `debug={true}` prop into the Popover, and then paste the contents of the log here.

**Comment by SteffeyDev** [comment]
I'll need to know a few things...
1) What are you passing in for `arrowStyle` and `popoverStyle`? The shadow issue is probably related to that.
2) What is the debug output? That will help me with the second issue

**Comment by Manoj002** [comment]
Hey @SteffeyDev 

here are the styles, 

```
popoverStyle = {{
      backgroundColor: '#fff',
      overflow: 'visible',
      shadowColor: '#d8d8d8',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 2,
}},
arrowStyle={{
      width: 32,
      height: 16,
      backgroundColor: '#fff',
      shadowColor: '#d8d8d8',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 2,
}}
```

**Comment by SteffeyDev** [comment]
I had to refactor a lot, but got this working.  Changes will be included in version 5.0.

**Comment by SteffeyDev** [comment]
Version 5.0.0 released, which includes a fix for this

**Comment by Mahalakshmi269** [comment]
https://github.com/SteffeyDev/react-native-popover-view/issues/135
In v4.1.0 it used to show shadow on the view but after updating to latest version shadow properties are not getting applied in android. In IOS it works as expected.
