### ISSUE TITLE
Event listener errors and warnings with `react-native` version 0.65.0 and later

### ISSUE THREAD

**Issue by matthesjh** [SteffeyDev/react-native-popover-view#117]
**Describe the bug**

Starting with `react-native` version 0.65.0 the method `Dimensions.removeEventListener` is deprecated and produces a warning when closing the popover. The `Dimensions.addEventListener` method now returns an `EventSubscription`, which can be used to remove the event listener (see https://github.com/facebook/react-native/commit/c47a03563db72d1580bf87b7729bd22ce6ca63dd). Furthermore `Keyboard.removeListener` produces an error when closing the popover, because this method has been removed (see https://github.com/facebook/react-native/commit/1049835b504cece42ee43ac5b554687891da1349).

**Device/Setup Info:**

- Device: iPad Pro 11-inch (3rd generation) [Simulator]
- OS: iOS 14.5
- `react-native` version: 0.65.1
- `react-native-popover-view` version: 4.0.2

**Comment by lucasfloriani** [comment]
#118 is a PR to fix this issue

**Comment by SteffeyDev** [comment]
Merged and released

**Comment by SteffeyDev** [comment]
Actually, #118 only fixed the keyboard part, not the dimensions

**Comment by SteffeyDev** [comment]
Looks like @types/react-native is not updated to 0.65.1 yet, so I can't change to using the subscription event yet because TypeScript won't build.  Once @types/react-native is updated, I can complete this pretty easily.

**Comment by KristofaJosh** [comment]
i'll be watching this.

**Comment by baatten** [comment]
I also have this warning all the time. waiting as well...

**Comment by matthesjh** [comment]
@SteffeyDev `@types/react-native` is now available in version `0.65.1`.

**Comment by baatten** [comment]
@SteffeyDev  any news on this? can you help with it please?

Morten

**Comment by SteffeyDev** [comment]
Released v4.1.0
