### ISSUE TITLE
Need callback on handleChange's animateTo

### ISSUE THREAD

**Issue by baron816** [SteffeyDev/react-native-popover-view#122]
**Is your feature request related to a problem? Please describe.**
I need to be able to trigger an action whenever the popover moves.

In my case, when the orientation of the device changes, my popover is going to move, but I have another tooltip that points to the popover. When that position changes, I need to notify the popover to move too.

**Describe the solution you'd like**
https://github.com/SteffeyDev/react-native-popover-view/blob/master/src/Popover.tsx#L797

Just add a `callback` property to the `animateTo` args object who's value is a new component prop (something like `onPositionChange`).

**Comment by SteffeyDev** [comment]
Merged and released v4.1.0
