### ISSUE TITLE
Cannot use functional components as "from"

### ISSUE THREAD

**Issue by AdamGerthel** [SteffeyDev/react-native-popover-view#128]
**Describe the bug**
Popover does not work when a functional component is supplied to the `from` prop. Error message reads:

> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

I don't know if this is intended behavior or not, and I'm not sure how to work around it.

**Device/Setup Info:**
Any device, see snack: https://snack.expo.dev/@insats/sample-popover

**Debug Output**

> calculateRectFromRef - waiting for ref

**Comment by AdamGerthel** [comment]
Solved by using `React.forwardRef()`

**Comment by SteffeyDev** [comment]
I'm actually going to re-open this so that I remember to update the documentation to mention this. Thanks for pointing it out.

**Comment by SteffeyDev** [comment]
Updated readme, added this under troubleshooting section.

**Comment by SteffeyDev** [comment]
Here are the generic react docs, including example: https://reactjs.org/docs/forwarding-refs.html

Just make sure to pass the ref to the outermost element, or the element that you want the popover to originate from.
