### ISSUE TITLE
ShadowOffset has wierd behaviour on iOS

### ISSUE THREAD

**Issue by adrianskogvold** [SteffeyDev/react-native-popover-view#129]
While using the popover I noticed an issue with shadowOffset on iOS, 

There are 2 usecases that I've seen so far: 

When just using the isVisible prop and  animating the popover in then the shadowOffset will be incorrect on the first render, but will be correct on sequential renders.
In the app I'm working on I remove it completely from the DOM when its not visible. And when that is the case then the shadowOffset will be incorrect at all times.
I've made a expo to show off both usecases: https://snack.expo.dev/@forestviolence/arrogant-cheese

On the app I'm working on I added a small hack to Popover.js that seems to fix the issue:

![image](https://user-images.githubusercontent.com/18528076/146396907-54901e31-e0cc-49a0-be28-c21d8a39fb9b.png)

Screenshots: 
First render: 
![image](https://user-images.githubusercontent.com/18528076/146393362-439667ad-6bc6-479c-b1d8-73517bd1dc15.png)
all following renders:
![image](https://user-images.githubusercontent.com/18528076/146393658-36c0b40d-5479-408b-a3f7-3762f8633b85.png)

**Comment by SteffeyDev** [comment]
Thanks for identifying this issue.  Can you please share the full code of your fix? The screenshot is making it difficult to tell what you changed.  A before and after would be even better.

**Comment by SteffeyDev** [comment]
Thanks for the details.  I'm actually unable to get `shadowOffset` working period now, both in your snack and in my own testing.  Are you still able to get it working with your modifications?

**Comment by SteffeyDev** [comment]
Looks like this was due to an issue in `Animated.View`. Moving shadow props to parent fixed. https://github.com/oblador/react-native-animatable/issues/133

**Comment by SteffeyDev** [comment]
Fix will be included in 5.0

**Comment by SteffeyDev** [comment]
Version 5.0.0 released, which includes many shadow-related fixes and improvements (see https://github.com/SteffeyDev/react-native-popover-view#upgrading)
