### ISSUE TITLE
why not use import {  ViewPropTypes } from 'react-native'？

### ISSUE THREAD

**Issue by hytStart** [SteffeyDev/react-native-popover-view#132]
https://github.com/SteffeyDev/react-native-popover-view/blob/d268481b271683da556ed51cf3aa1d13b84ef112/src/Popover.tsx#L85

```
const stylePropType = isWeb ? PropTypes.object : ViewPropTypes.style
```

**Comment by SteffeyDev** [comment]
Thanks, closing in favor of #133
