### ISSUE TITLE
Popover does not show if isVisible is initially true

### ISSUE THREAD

**Issue by SM-Wistful** [SteffeyDev/react-native-popover-view#14]
I pasted the "Standalone" example into my project. At the top of the file:

```import Popover from 'react-native-popover-view'```

In render: 

```
<Popover
      isVisible={this.state.isVisible}>
      <Text>Hello, world.</Text>
</Popover>
```

It simply does not work... there are no errors but nothing shows up. I am using an iOS simulator (yes, `this.state.isVisible` is true).  Is there some other setup required or what? I thought the width and size props were optional.

**Comment by SM-Wistful** [comment]
Okay, well it seems to me like isVisible CAN'T start off as true.

**Comment by SM-Wistful** [comment]
Thanks! The work you've done is awesome, I was just confused a bit at the start as I wanted to have it visible automatically for debugging purposes :)

**Comment by SteffeyDev** [comment]
I’m glad you find it useful!  I could probably add support for that, I’ll look into it to see how hard it would be.

**Comment by SteffeyDev** [comment]
Ok, it should now work with isVisible set to true initially, if you want to test and let me know if it works for you that would be great!
