### ISSUE TITLE
changing typescript 

### ISSUE THREAD

**Issue by kwangjaeyoo** [SteffeyDev/react-native-popover-view#142]
`react-native` version: 0.66.4
`react-native-popover-view` 5.0.1
"typescript": "^4.7.2"
------------------------------------

I'm switching to typescript.
I get this log in vscode.
It works normally in the simulator(ios, android) and device.
error log from vscode.

------------------------------

No overload matches this call.
  Overload 1 of 2, '(props: PublicPopoverProps | Readonly<PublicPopoverProps>): Popover', gave the following error.
    Type '{ children: Element; from: Element; isVisible: boolean; placement: Placement.BOTTOM; onRequestClose: () => void; onCloseComplete: () => void; arrowStyle: { backgroundColor: string; height: number; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Popover> & Pick<Pick<Readonly<PublicPopoverProps>, keyof PublicPopoverProps> & Pick<...> & Pick<...>, never> & InexactPartial<...> & InexactPartial<...>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Popover> & Pick<Pick<Readonly<PublicPopoverProps>, keyof PublicPopoverProps> & Pick<...> & Pick<...>, never> & InexactPartial<...> & InexactPartial<...>'.
  Overload 2 of 2, '(props: PublicPopoverProps, context: any): Popover', gave the following error.
    Type '{ children: Element; from: Element; isVisible: boolean; placement: Placement.BOTTOM; onRequestClose: () => void; onCloseComplete: () => void; arrowStyle: { backgroundColor: string; height: number; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Popover> & Pick<Pick<Readonly<PublicPopoverProps>, keyof PublicPopoverProps> & Pick<...> & Pick<...>, never> & InexactPartial<...> & InexactPartial<...>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Popover> & Pick<Pick<Readonly<PublicPopoverProps>, keyof PublicPopoverProps> & Pick<...> & Pick<...>, never> & InexactPartial<...> & InexactPartial<...>'.

------------------------------

my code ----

 // <View>
 //         {/* TODO_Popover */}
 //         <Popover
 //           from={
 //             <TouchableOpacity
 //               onPress={() => setOpenModal(true)}
 //               style={QListStyle.imgMoreIcon}>
 //               <Image source={require('../../img/more_btn.png')} />
 //             </TouchableOpacity>
 //           }
 //           isVisible={openModal}
 //           placement={PopoverPlacement.BOTTOM}
 //           onRequestClose={() => {
 //           setOpenModal(false);
 //           }}
 //           arrowStyle={{backgroundColor: 'transparent', height: 0}}>
 //           <View style={[Style.dropdown__popup__option, {minWidth: 150}]}> 
 //           
//           </View>
//        </Popover>
//  </View>

**Comment by SteffeyDev** [comment]
Thanks for bringing this to my attention, fixed in 5.1.1

**Comment by kwangjaeyoo** [comment]
Thank you for fixed this !
