### ISSUE TITLE
Does not function on certain devices

### ISSUE THREAD

**Issue by SM-Wistful** [SteffeyDev/react-native-popover-view#16]
Hello! 

It works perfectly in the iOS simulator; however, I have tested on a physical device (both iPhone and iPad) and it does not render.

In fact, trying to present the popover actually crashes the app with no error... it just freezes. I really liked this library but this is a deal-breaker. I am building with Xcode 9.4.1

**Comment by SM-Wistful** [comment]
Okay, further inspection reveals that it's not crashing the app, it just seems like it's rendering incorrectly and covering the entire screen.

**Comment by surendharreddy** [comment]
Thanks for reporting it @SM-Wistful, I also faced this issue in production. In my case, it was working fine on iPhone X but not on other iOS devices.

**Comment by SteffeyDev** [comment]
@SM-Wistful Can you download my Test App (https://expo.io/@steffeydev/popover-view-test-app) on those physical devices and see if it works inside there?  You will need to download the Expo app first.

**Comment by SteffeyDev** [comment]
If it works inside the test app but not in your app, I invite you to look at the test app source code to see if you can find the difference, and I would be happy to help you in that, as I want this library to work in as many situations as possible.  If it does not work in the test app, let me know what models don’t work and I will try to get a hold of the device to test on.

**Comment by SteffeyDev** [comment]
I just pushed an update with a number of fixes, check out version 1.0.7 to see if the issue still persists.  If it does, please check out my troubleshooting steps above.

**Comment by SM-Wistful** [comment]
Hi! Sorry for taking so long to get back to you on this. I don't have my iPad available right now, but I will test it tomorrow and let you know. Thanks for all the work you are doing on this :)

**Comment by SteffeyDev** [comment]
No logs, but did you try out the expo test app?

**Comment by SM-Wistful** [comment]
I can do that, but it seems unlikely my app is the issue. The exact same app works perfectly on iPhones, but breaks when I run it on an iPad...

**Comment by SteffeyDev** [comment]
That’s fine, my test app will give you a range of popovers to test on device so we can try and pinpoint the exact issue

**Comment by drewvolz** [comment]
I enabled debug in `react-native-popover-view` and it appears we're sitting on `measureContent()`.

The last line in debug is from Popover.js line 145.

https://github.com/SteffeyDev/react-native-popover-view/blob/59140c995b46199e9badbb618970e10b0e01b6c0/src/Popover.js#L141-L146

`measureContent - Waiting - requestedContentSize`

Log | Line
--|--
componentWillReceiveProps - Awaiting popover show | Popover.js 503
setDefaultDisplayArea - newDisplayArea: {"x":10,"y":10,"width":394,"height":716} |  Popover.js 58
measureContent - Waiting - requestedContentSize: {"y":0,"width":257,"x":0,"height":653} |  Popover.js:145
measureContent - Waiting - requestedContentSize: {"y":0,"width":257,"x":0,"height":653} |  Popover.js 145

**Comment by SteffeyDev** [comment]
I don't have a way of testing against older iOS versions, but it may have to do with RN's SafeAreaView on older versions.  @drewvolz Try putting `if (DEBUG) console.log(this.safeAreaViewReady);` after line 145, this will tell us if that is the issue.  If it is, I can make the safeAreaView check only active on iOS versions >= 11.

**Comment by SteffeyDev** [comment]
According to https://github.com/facebook/react-native/issues/17638 and https://github.com/facebook/react-native/issues/18255, it looks like SafeAreaView does not support iOS 10 and below.  I'll either add a version check or switch to https://github.com/react-community/react-native-safe-area-view.

**Comment by SteffeyDev** [comment]
I'm downloading iOS 10.3.1 and iOS 9.3 simulators now so I can test

**Comment by drewvolz** [comment]
@SteffeyDev adding `if (DEBUG) console.log(this.safeAreaViewReady);` after line 145 on iOS 9.3 comes back as `true` when trying to activate the popover.

**Comment by SteffeyDev** [comment]
Ok, thanks for testing that.  It looks like RN’s SafeAreaView just doesn’t do anything on versions older than iOS 11, so I’m switching to `react-native-safe-area-view`, which unfortunately has a number of drawbacks in it’s own implementation, so once I find a way to accomadate those I will be able to push a fix.

**Comment by drewvolz** [comment]
Let us know if there's anything we can do to help. We appreciate you looking into switching to `react-native-safe-area-view` and dealing with the unfortunate drawbacks.

**Comment by SteffeyDev** [comment]
Ok, check out v1.0.9 and let me know how it works for you!

**Comment by drewvolz** [comment]
v1.0.9 does fix the issue we were seeing iOS 9 👍

**Comment by SM-Wistful** [comment]
Yeah, I can confirm that this update fixes it on iOS 9!! Thank you :)
