### ISSUE TITLE
hide statusbar

### ISSUE THREAD

**Issue by arifsuheyl** [SteffeyDev/react-native-popover-view#162]
I can't hide the status bar when popover is visible on Android. While popover model is closed, it's gone but status bar appears with popover. This does not happen in IOS. How can I solve this?

**Comment by phuoctai12t** [comment]
@arifsuheyl use statusBarTranslucent={true} prop, the typescript declaration is missing it.

**Comment by gpbaculio** [comment]
@phuoctai12t possible to hide without height?

**Comment by AdamGerthel** [comment]
I have the same issue - both navigation (hidden through expo-navigation-bar) and statusbar appears when the popover opens.

**Comment by AdamGerthel** [comment]
Closing as this is because of `Modal` and is not something that this package can resolve. Here's a potential workaround: https://github.com/facebook/react-native/issues/37801#issuecomment-1817135998
