### ISSUE TITLE
error: bundling failed: Error: Unable to resolve module `../../react-navigation/src/views/StackView/StackView`

### ISSUE THREAD

**Issue by reilem** [SteffeyDev/react-native-popover-view#17]
Thanks for all the work put into this repo. It works really well. However I tried upgrading to react-navigation v2.12.1 and I keep getting this error:

> error: bundling failed: Error: Unable to resolve module `../../react-navigation/src/views/StackView/StackView` from `/.../node_modules/react-native-popover-view/src/PopoverStackNavigator.js`: The module `../../react-navigation/src/views/StackView/StackView` could not be found from `/..../node_modules/react-native-popover-view/src/PopoverStackNavigator.js`. Indeed, none of these files exist:

I am not using this library for react navigation integration, I just want the component. Is there a way to turn off this react-navigation integration option? It is causing more headaches than it solves.

I'm using v1.0.5 of this repo.

**Comment by SteffeyDev** [comment]
There is a way, but it’s not the most straight forward. I do know that they were doing refracting in 2.12.1, so I’ll have to refactor as well. 

As you are not the first to run into this problem, I’m thinking of breaking this into two different npn repositories, one for react-navigation integration and one for not. I have an idea of how to do it, so I’ll give it a go tonight and let you know if it works. 

In the meantime, you could downgrade react-navigation (just until I address this)

**Comment by SteffeyDev** [comment]
Ok, I have now split react-native-popover-view into two libraries!  I moved all of the react-navigation stuff into `react-navigation-popover` and updated to work with 2.12.x, and now this repository only contains the base popover.  Let me know if this fixes your issue!
