### ISSUE TITLE
Popover doesn't return to initial position after being shifted by keyboard

### ISSUE THREAD

**Issue by duchunter** [SteffeyDev/react-native-popover-view#18]
- Before keyboard show:
![screenshot_2018-08-31-11-20-36-526_host exp exponent](https://user-images.githubusercontent.com/23138920/44892703-76433c80-ad10-11e8-94a2-0390ef8ce115.png)
- After keyboard hide:
![screenshot_2018-08-31-11-20-48-202_host exp exponent](https://user-images.githubusercontent.com/23138920/44892714-82c79500-ad10-11e8-80b5-34a581f16454.png)

**Comment by SteffeyDev** [comment]
It is working as expected on my iPhone X, what device and OS is the issue on?

**Comment by duchunter** [comment]
I have this issue on my phone - Redmi 3S android 6.0.1, and my emulator Nexus 5X android 7.1.1
