### ISSUE TITLE
Popover not working in Android with RN 0.76.1 Bridgeless disabled

### ISSUE THREAD

**Issue by smfunder** [SteffeyDev/react-native-popover-view#183]
**Describe the bug**

In RN 0.76.1 with bridgeless mode false when you try to tap on the "from" part of the Popover it just hangs on Android without showing the Popup and the UI comes unresponsive.

**Device/Setup Info:**
 - Device: Samsung Galaxy S20 FE
 - OS: Android 13
 - `react-native` version: 0.76.1
- `react-native-popover-view` version: 5.1.9

**Debug Output**
When tapping on the "from" I was getting this:

 INFO  2024-11-17T02:01:44.198Z [2024-11-17T02:01:44.198Z] calculateRectFromRef - waiting for ref
 INFO  2024-11-17T02:01:44.202Z [2024-11-17T02:01:44.201Z] calculateRectFromRef - waiting for ref to move from: {"x":0,"y":0,"width":0,"height":0}

And nothing else. Just hanged there as well as the Android UI.

**Comment by smfunder** [comment]
After some fixes, I had to modify the source code in the `/src` folder, and the build the app with `npm run build`.

The core change was to modify the function `getRectForRef` in the `Utility.ts` file to this:

```
export function getRectForRef(ref: RefType): Promise<Rect> {
  return new Promise((resolve, reject) => {
    if (Platform.OS === 'android') {
      if (!ref.current) {
        reject(new Error("Reference is not set or the component is not mounted"));
        return;
      }
  
      // Wait for the next layout event
      (ref.current as any).measure((x: number, y: number, width: number, height: number, _pageX: number, _pageY: number) => {
        resolve(new Rect(Number(_pageX), Number(_pageY), Number(width), Number(height) ));
      });
    } else {
      if (ref.current) {
        NativeModules.UIManager.measure(
          findNodeHandle(ref.current),
          (_1: unknown, _2: unknown, width: number, height: number, x: number, y: number) =>
            resolve(new Rect(x, y, width, height))
        );
      } else {
        reject(new Error('getRectForRef - current is not set'));
      }
    }
  });
}
```

But to do this work, I had to update tsconfig file in order to build the library.

So in the end here is my patch-package file to patch the library and make it work in Android. I'm not pretty sure how to suggest a PR here in the correct way, so that's why I post the .patch file.


[react-native-popover-view+5.1.9.patch](https://github.com/user-attachments/files/17788815/react-native-popover-view%2B5.1.9.patch)

**Comment by smfunder** [comment]
I agree with this PR: https://github.com/SteffeyDev/react-native-popover-view/pull/182

**Comment by narendratailwnd** [comment]
> After some fixes, I had to modify the source code in the `/src` folder, and the build the app with `npm run build`.
> 
> The core change was to modify the function `getRectForRef` in the `Utility.ts` file to this:
> 
> ```
> export function getRectForRef(ref: RefType): Promise<Rect> {
>   return new Promise((resolve, reject) => {
>     if (Platform.OS === 'android') {
>       if (!ref.current) {
>         reject(new Error("Reference is not set or the component is not mounted"));
>         return;
>       }
>   
>       // Wait for the next layout event
>       (ref.current as any).measure((x: number, y: number, width: number, height: number, _pageX: number, _pageY: number) => {
>         resolve(new Rect(Number(_pageX), Number(_pageY), Number(width), Number(height) ));
>       });
>     } else {
>       if (ref.current) {
>         NativeModules.UIManager.measure(
>           findNodeHandle(ref.current),
>           (_1: unknown, _2: unknown, width: number, height: number, x: number, y: number) =>
>             resolve(new Rect(x, y, width, height))
>         );
>       } else {
>         reject(new Error('getRectForRef - current is not set'));
>       }
>     }
>   });
> }
> ```
> 
> But to do this work, I had to update tsconfig file in order to build the library.
> 
> So in the end here is my patch-package file to patch the library and make it work in Android. I'm not pretty sure how to suggest a PR here in the correct way, so that's why I post the .patch file.
> 
> [react-native-popover-view+5.1.9.patch](https://github.com/user-attachments/files/17788815/react-native-popover-view%2B5.1.9.patch)

i try above solution but still same issue popover not show.

**Comment by smfunder** [comment]
@narendratailwnd after applying the patch / update the code, did you run the command on the `node_modules/react-native-popover-view` -> `npm run build` and re-run the app cleaning the code?

**Comment by MobileMon** [comment]
it does not work for me either

it still freezes

**Comment by yhanssens** [comment]
The provided patch fixes the freezing part, the popover however is not showing.

**Comment by MobileMon** [comment]
this is a hot fix for now

export function getRectForRef(): Promise<Rect> {
  return new Promise((resolve) => {
    const { width, height } = Dimensions.get('window');
    // Just pick a default size for the popover or let the popover manage its own size.
    // For now, we’ll just provide coordinates, width, and height that center it.
    const popoverWidth = 200;
    const popoverHeight = 300;

    const x = (width - popoverWidth) / 2;
    const y = (height - popoverHeight) / 2;
    resolve(new Rect(x, y, popoverWidth, popoverHeight));
  });
}


it just draws the popover in the middle of the screen. better than nothing until we get a proper fix

**Comment by AdamGerthel** [comment]
See https://github.com/SteffeyDev/react-native-popover-view/releases/tag/v6.0.0
