### ISSUE TITLE
Popover: Translate Point value is null

### ISSUE THREAD

**Issue by tal987** [SteffeyDev/react-native-popover-view#24]
Hi, im getting this error sometimes and I don't understand what does it mean and how to solve it... I would like for some explanation

**Comment by SteffeyDev** [comment]
I’d love to help... can you post the code snippet of how you are using the popover so that I can track down the issue?

**Comment by tal987** [comment]
`    <Popover
          isVisible={this.state.entryPopUpVisible}
          onClose={() => this.closeEntryPopover()}
          arrowStyle={{ backgroundColor: 'transparent' }}>
          <Text> I'm the content of this popover! {"\n"}
            Entry to room {this.state.roomEntry}!!!
          </Text>
        </Popover>`

**Comment by SteffeyDev** [comment]
Also, what behavior do you see when this error occurs?  Is it preventing the functioning of the Popover component or is it just annoying to have this in your logs and not know why?

**Comment by tal987** [comment]
@SteffeyDev I don't see the popover at all only when I refresh the screen (cmd+R) the pop over show up

**Comment by tal987** [comment]
@SteffeyDev do I miss anything? im trying to have this popover in the middle of the screen on landscape mode without pressing anything

**Comment by SteffeyDev** [comment]
Your code should show the Popover centered on the screen when `this.state.entryPopUpVisible` is true.  What do you mean by:

> I don't see the popover at all only when I refresh the screen (cmd+R) the pop over show up

Does the popover not show when you first boot the app but it does show on subsequent reloads?
