### ISSUE TITLE
Multiple Popovers opening in sequence, second not opening when triggered by button in first

### ISSUE THREAD

**Issue by huynguyen2903** [SteffeyDev/react-native-popover-view#27]
Sorry for my bad English.
I want to use react-native-popover-view as a guide for new user. If user read the first guide and they click "Ok" it will open the second guide. My code is below.
Thank you for your help !
"react-native-popover-view": "version": "1.0.9",
"react-native": "version": "0.57.4",

```
export default class App extends Component<Props> {
  componentDidMount() {
    this.setState({ isVisible: true });
  }
  state = {
    isVisible: false,
    isVisible2: false
  };

  showPopover() {
    this.setState({ isVisible: true });
  }
  showPopover2() {
    this.setState({ isVisible2: true });
    this.setState({ isVisible: false });
  }

  closePopover() {
    this.setState({ isVisible: false });
  }
  render() {
    return (
      <View style={styles.container}>
        <Popover
          isVisible={this.state.isVisible}
          fromView={this.touchable}
          onClose={() => this.closePopover()}
        >
          <Text style={styles.test}>The first guide</Text>
          <TouchableHighlight
            style={styles.button}
            onPress={() => this.showPopover2()}
          >
            <Text>go to second</Text>
          </TouchableHighlight>
        </Popover>
        <Popover
          isVisible={this.state.isVisible2}
          fromView={this.touchable2}
          onClose={() => this.closePopover()}
        >
          <Text style={styles.test}>The second guide</Text>
          <TouchableHighlight
            style={styles.button}
            onPress={() => this.showPopover()}
          >
            <Text>Press me</Text>
          </TouchableHighlight>
        </Popover>

        <TouchableHighlight
          ref={ref => (this.touchable = ref)}
          style={styles.button}
          onPress={() => this.showPopover()}
        >
          <Text>Press me</Text>
        </TouchableHighlight>
        <Text
          ref2={ref2 => (this.touchable2 = ref2)}
          tyle={styles.instructions}
        >
          text 1
        </Text>
      </View>
    );
  }
}

```

**Comment by SteffeyDev** [comment]
That code looks like it should work, what is not working? If the second popover is not showing when you click the button, you could try
```
showPopover2() {
  this.setState({ isVisible2: true }, () => this.setState({ isVisible: false }));
}
```
or
```
<Popover
  isVisible={this.state.isVisible}
  fromView={this.touchable}
  doneClosingCallack={() => this.setState({ isVisible2: true })}
  onClose={() => this.setState({ isVisible: false })}
  >
  <Text style={styles.test}>The first guide</Text>
  <TouchableHighlight
    style={styles.button}
    onPress={() => this.setState({ isVisible: false })}
  >
    <Text>go to second</Text>
  </TouchableHighlight>
</Popover>
```

Using the `doneClosingCallback` will make sure the second popover doesn't trigger until the first one is done closing.

**Comment by huynguyen2903** [comment]
it's still not working. The second popover didn't show. it's work for you ?

**Comment by huynguyen2903** [comment]
The state of isVisible2 was changed "true" but the popover 2 not showing

**Comment by SteffeyDev** [comment]
I'm considering making a change to the popover code to make this easier, which would detect when there is a modal open and then delay the second popover from trying to show until the first is closed... so you are welcome to wait for that update, but no guarantee on timing.

**Comment by huynguyen2903** [comment]
I can't set timeout for this because my client request that popover will be closed when user click on button.
I try showInModal={false} it's work but the popover is overplay component. How can I fix it. The picture is below.
![image](https://user-images.githubusercontent.com/40721082/47696156-14cc1b00-dc38-11e8-854b-742c0d04cd60.png)

**Comment by SteffeyDev** [comment]
And `showInModal={false}` is actually not working currently, I haven't tested in a while, but I fixed last night and it will work in the next release.  I think your best bet is with the timeout or `doneClosingCallback`.

**Comment by huynguyen2903** [comment]
It's work. 
Thank you very much @SteffeyDev.
