### ISSUE TITLE
RTL support not provided. PopOver view does not display when app switched to RTL

### ISSUE THREAD

**Issue by RadhikaPadiyar** [SteffeyDev/react-native-popover-view#36]
**Describe the bug**
What is it that you are seeing?  Please be detailed in your description so that I can help fix your issue as quickly as possible.

**Device/Setup Info:**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 8.1]
 - `react-native` version: [e.g. 0.57.1]
- `react-native-popover-view` version: [e.g. 1.0.7]

**Screenshots**
If there is a visual issue, add screenshots or a video so that I can see what is going on.

**Debug Output**
Pass the `debug={true}` prop into the Popover, and then paste the contents of the log here.

**Comment by SteffeyDev** [comment]
You created an issue but didn't fill out the details?  The template above is a _template_, designed so that you fill out the section with your own details.  Please fill out some of the details so that I can reproduce and debug (esp. the description and device/setup info)

**Comment by SteffeyDev** [comment]
With no response for 2 months, I am closing this.  Though I do care about your issue, you've given me so little details that I can't start looking into this.  Please open a new issue with more details if this is still a problem.
