### ISSUE TITLE
Update react

### ISSUE THREAD

**Issue by tokinonagare** [SteffeyDev/react-native-popover-view#42]
Event componentWillRecieveProps will deprecate after updating react.
Use getDerivedStateFromProps() and componentDidUpdate() instead componentWillReceiveProps();

**Comment by SteffeyDev** [comment]
Not sure how I missed this coming in, but I did see the update coming up and will try to roll out a compatible release soon.

**Comment by SteffeyDev** [comment]
Ok, updated to latest react with 2.0.2
