### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by mattyx96** [SteffeyDev/react-native-popover-view#5]
Thank you for this beautiful work
I know that this library have problems with android 
I tryed this library on my project (android) and i noticed that the pop over is displayed only if i rotate the display after call the show pop over function
Maybe this can help you to fix
When do you think this library will support android?

**Comment by SteffeyDev** [comment]
Yes, I identified the issue and already have a fix for Android.  I was holding of releasing because I found another bug on Android, but I'll go ahead and push the fix and tackle the bug later.

**Comment by mattyx96** [comment]
Good, i hope that this library will be available as soon as possible

**Comment by SteffeyDev** [comment]
Ok, I just pushed the new version 0.6.4, let me know if it works for you!

**Comment by mattyx96** [comment]
Can't find variable: PopoverStackNavigator

I have not used any PopoverStackNavigator

**Comment by SteffeyDev** [comment]
Does your project have react-navigation as a dependency?

**Comment by SteffeyDev** [comment]
I see the same error, but I have absolutely no clue why

**Comment by SteffeyDev** [comment]
Ok, for some reason it published the wrong branch, try 0.6.5, it should be fixed now

**Comment by mattyx96** [comment]
It works!
