### ISSUE TITLE
animationConfig not valid in typescript 3.6.3

### ISSUE THREAD

**Issue by AndrewMorsillo** [SteffeyDev/react-native-popover-view#50]
Setting animationConfig to `{duration: 100}` results in a TS error. Maybe something changed on the RN side of the type definitions?

```
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<PopoverViewProps>): Popover', gave the following error.
    Property 'toValue' is missing in type '{ duration: number; }' but required in type 'TimingAnimationConfig'.
  Overload 2 of 2, '(props: PopoverViewProps, context?: any): Popover', gave the following error.
    Property 'toValue' is missing in type '{ duration: number; }' but required in type 'TimingAnimationConfig'.
```

 - `react-native` version: 0.60.5
- `react-native-popover-view` version: 2.0.5
- `typescript` version: 3.6.3

edit: small additional unrelated TS issue, Popover.MODE constants aren't in the .d.ts file resulting in TS errors when they are referenced.

**Comment by SteffeyDev** [comment]
Just converted the whole thing to typescript, so this should be fixed.  Re-open if it is still an issue.
