### ISSUE TITLE
Popover is shown under text elements

### ISSUE THREAD

**Issue by ronilitman** [SteffeyDev/react-native-popover-view#54]
**Describe the bug**
I am using the component with tooltip mode. It is shown under text. z index won't help. Does anyone know what I might be doing wrong?
Thank you!

**Screenshots**
![image](https://user-images.githubusercontent.com/13034976/68397047-3b8e2d00-017b-11ea-906c-e1f243c6709f.png)

**Comment by SteffeyDev** [comment]
The order of your react components are important.  Assuming that you are not using z-index anywhere, the elements that are farther down in the code will render above elements that were listed before them. Try moving the popover beneath the fields in the code and at a higher nesting level to ensure it shows above.

**Comment by SteffeyDev** [comment]
https://unbug.gitbooks.io/react-native-training/content/32_absolute_&_relative.html

**Comment by SteffeyDev** [comment]
If you can’t get it working, create a snack that demonstrates the issue and I will take a look

**Comment by SteffeyDev** [comment]
Also, you can check out my test app to see a tooltip rendering correctly, maybe learn something from inspecting that code: https://github.com/SteffeyDev/react-native-popover-view-test-app

**Comment by ronilitman** [comment]
@SteffeyDev it worked, thanks for your help. What I actually missed is the fact that default position in react native is relative, and this is why my other elements are "winning". Small question though - why zIndex won't work in this case? Thanks again!

**Comment by SteffeyDev** [comment]
I suspect that zIndex has to be used in tandem with absolute positioning, so if you have a mix of absolute and relatively positioned elements then the order may be weird.  I tend to avoid zIndex for exactly that reason.  Wish I could give a better answer but I think it is one of those parts of React Native that I will never fully grasp.  Glad you got it working!
