### ISSUE TITLE
How can we change the color of text inside tooltip?

### ISSUE THREAD

**Issue by ankur-1989** [SteffeyDev/react-native-popover-view#58]
I want to change the background color of popover view to grey and text color to white. But it seems not to be possible. How can I achieve that?

**Comment by SteffeyDev** [comment]
You can pass the backgroundColor into popoverStyle prop

**Comment by SteffeyDev** [comment]
And then you control the text color obviously, as you have full control over all popover content

**Comment by ankur-1989** [comment]
yup got it. Thanks for the help!!!
