### ISSUE TITLE
Make style attributes accept an array

### ISSUE THREAD

**Issue by exotexot** [SteffeyDev/react-native-popover-view#65]
It would be cool if the popoverStyle prop (and all other style props, would accept an array as all other RN elements with style prop do. The background here is to apply different styles through a hook (e.g. react-navigations useTheme hook).

 const { colors } = useTheme()
<View style={[styles.modal, { backgroundColor: colors.background }]}>

**Comment by SteffeyDev** [comment]
Oh I agree that would be cool, I'll try to include that in the next release.  For now, you can just use `popoverStyle={StyleSheet.flatten(<array>)}`.

**Comment by SteffeyDev** [comment]
Ok, this is implemented in the latest release 3.0.0
