### ISSUE TITLE
Type error when using with Typescript

### ISSUE THREAD

**Issue by abdulhaseeb07a** [SteffeyDev/react-native-popover-view#68]
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<PublicPopoverProps>): Popover', gave the following error.
    Type '{ children: Element; mode: Mode.TOOLTIP; placement: Placement.TOP; isVisible: boolean; from: Element; }' is missing the following properties from type 'Pick<Pick<Readonly<PublicPopoverProps> & Readonly<{ children?: ReactNode; }>, "children" | "isVisible" | "from" | "displayArea" | ... 13 more ... | "mode"> & Pick<...> & Pick<...>, "children" | ... 8 more ... | "backgroundStyle">': popoverStyle, arrowStyle, backgroundStyle
  Overload 2 of 2, '(props: PublicPopoverProps, context?: any): Popover', gave the following error.
    Type '{ children: Element; mode: Mode.TOOLTIP; placement: Placement.TOP; isVisible: boolean; from: Element; }' is missing the following properties from type 'Pick<Pick<Readonly<PublicPopoverProps> & Readonly<{ children?: ReactNode; }>, "children" | "isVisible" | "from" | "displayArea" | ... 13 more ... | "mode"> & Pick<...> & Pick<...>, "children" | ... 8 more ... | "backgroundStyle">': popoverStyle, arrowStyle, backgroundStyle

Source Code (Get it from doc)
`<Popover
                            mode={PopoverMode.TOOLTIP}
                            placement={PopoverPlacement.TOP}
                            isVisible={showPopover}
                            from={(
                              <TouchableOpacity onPress={() => setShowPopover(true)}>
                                <Text>Press here to open popover!</Text>
                              </TouchableOpacity>
                            )}>
                            <>
                              <Text>This is the contents of the popover</Text>
                              <TouchableOpacity onPress={() => setShowPopover(false)}>
                                <Text>Dismiss</Text>
                              </TouchableOpacity>
                            </>
                          </Popover>`

**Comment by SteffeyDev** [comment]
Sorry about that.  Can you try out 3.0.1? I made most of the props optional now.  Let me know if it doesn't work and I can spend more time on a fix.  Just wanted to see if I could get a quick fix out.
