### ISSUE TITLE
Unable to resolve module `.../../react-navigation/src/views/CardStack/CardStackTransitioner`

### ISSUE THREAD

**Issue by eric101110** [SteffeyDev/react-native-popover-view#7]
Unable to resolve module `.../../react-navigation/src/views/CardStack/CardStackTransitioner`

\node_modules\react-native-popover-view\src\PopoverStackNavigator.js`: Module does not exist in the module map

I have  "react-navigation": "^1.5.11", installed

**Comment by SteffeyDev** [comment]
Unfortunately, I have not updated to the latest version of react-navigation yet. Upgrading is a fairly involved process, as I have to find which files I need to overwrite for it to behave properly. If you know anything about react-navigation in depth, I could definitely use the expertise. If not, I will try to get on it this weekend.

**Comment by SteffeyDev** [comment]
Ok, that was fun.  @eric101110 `react-native-popover-view@1.0.x` now supports `react-navigation@2.0.1`, go ahead and check it out when you have the chance!  Not sure if it will work with `react-navigation@1.5.11`, but you can always try it out and let me know.

**Comment by SteffeyDev** [comment]
Closing, @eric101110 let me know if this doesn't work for you
