### ISSUE TITLE
Not working on react-native-web

### ISSUE THREAD

**Issue by nathanclevenger** [SteffeyDev/react-native-popover-view#77]
**Describe the bug**
The popover works fine on iOS and Android, but not react-native-web (at least on Chrome or Safari with Expo)

**Device/Setup Info:**
 - Device: Mac OS X 
 - OS: Catalina 10.15.5
 - `react-native` version: Expo 38.0.0
- `react-native-popover-view` version: 3.0.3

**Repro**
https://snack.expo.io/m3hEW9eqE

**Debug Output**
Pass the `debug={true}` prop into the Popover, and then paste the contents of the log here.

**Comment by SteffeyDev** [comment]
Yep, looks like web support is hit or miss.   I changed the readme to reflect this, as I don't have time to support web right now.  Open to PRs for better web support, however.
