### ISSUE TITLE
Add GIFs to the readme

### ISSUE THREAD

**Issue by nandorojo** [SteffeyDev/react-native-popover-view#87]
I think the readme is really nicely documented. It would be useful if the different use-cases had a short GIF. For example, the tooltip vs normal usage would be nice to see. Just a suggestion.

**Comment by IkaroAlef** [comment]
Inside the folder [react-native-popover-view/Screenshots/](https://github.com/SteffeyDev/react-native-popover-view/tree/master/Screenshots) there are some examples. I hope it helps.

**Comment by SteffeyDev** [comment]
Oh man I forgot those exist and they are very outdated. Adding new ones to the readme is a good idea.

**Comment by hirbod** [comment]
I was about to write the exact same issue. I think most of the solid libs with very little "star count" are most likely due to missing screenshots. And they should be at the TOP of the readme. I usually tend to skip libs without them.

**Comment by SteffeyDev** [comment]
Done!
