### ISSUE TITLE
Add parameters to control animations

### ISSUE THREAD

**Issue by tslater** [SteffeyDev/react-native-popover-view#9]
I have different situations where the default animation is acting strange. I'd like the ability to adjust duration, easing, or turn it off altogether.

**Comment by SteffeyDev** [comment]
That can be done; if you do a PR I’ll push it through, or I’ll do it myself as soon as I have the chance.

**Comment by SteffeyDev** [comment]
@tslater Ok, version 1.0.1 on NPM now contains an `animationConfig` prop.  You can override any animation options, and my `react-native-popover-view-test-app` expo project demonstrates how you can disable animations using `animationConfig={{ duration: 0 }}`.  Of course you can also change the easing and other animation properties.

**Comment by tslater** [comment]
That is super awesome! Thanks a bunch. I'll try it out.
