### ISSUE TITLE
Feels like it's slowly opening

### ISSUE THREAD

**Issue by ajoykarmakar** [SteffeyDev/react-native-popover-view#91]
**Describe the bug**
When I am clicking the button the popover opening animation looks slow. Like I have to wait half second but my animation duration in 200. Maybe the animation configuration is ease in out, Can we start the animation with linear animation style?

**Device/Setup Info:**
 - Device: Emulator / Real Devices
 - OS: Android 7,8,10
 - "react": "16.13.1",
 - "react-native": "0.63.4"

**Comment by SteffeyDev** [comment]
You can control the easing through the `animationConfig` prop. Please reference the README.

**Comment by SteffeyDev** [comment]
It is worth noting that the performance of the device is a factor here, as it has to complete one or two render and calculation cycles before the Popover animation actually starts.  This is due to the complex nature of calculating the position and animation properties when the source button could be anywhere on the screen.

**Comment by ajoykarmakar** [comment]
Hello there, Thank you for the response. In the documentation -   ` animationConfig = {{ duration: 600, easing: Easing.inOut(Easing.quad) })}` But how should I implement the linear animation style? I can't found the appropriate options.

**Comment by SteffeyDev** [comment]
https://reactnative.dev/docs/easing

You will have to read up on RN Easing to find the function you want. The example in the README is just that, and example.

**Comment by Hansraj8149** [comment]
> It is worth noting that the performance of the device is a factor here, as it has to complete one or two render and calculation cycles before the Popover animation actually starts. This is due to the complex nature of calculating the position and animation properties when the source button could be anywhere on the screen.

Hii @SteffeyDev is there any way we can make it faster like skipping this position calculation and by providing a position

**Comment by AdamGerthel** [comment]
The speed was recently increased a bit (see https://github.com/SteffeyDev/react-native-popover-view/issues/177). With that said, yes, it's probably possible to add support for a fixed position.

PR's are welcome! I'd suggest that the `placement` prop gets support for passing a `Rect` object. See [this section of the readme](https://github.com/SteffeyDev/react-native-popover-view?tab=readme-ov-file#contributing) on how to contribute.
