### ISSUE TITLE
Arrow origin issue for item partially out of view in the left

### ISSUE THREAD

**Issue by RajRohitYadav** [SteffeyDev/react-native-popover-view#97]
**Describe the bug**
If Origin of popover goes out of view even a little bit on the left side, the popover arrow starts from the edge of the device. Ideally, the arrow should start from the edge of the origin. Can be compared with the right side for verificaion. Check the video below.

**Device/Setup Info:**
 - Device: iPhone 12 (Simulator)
 - OS: iOS 14.4
 - `react-native` version: 17.0.1
- `react-native-popover-view` version: 3.1.1

**Video**
https://www.youtube.com/watch?v=57CpNwRoZ3w

**Screenshots**
https://user-images.githubusercontent.com/12390240/114262919-2a94bb80-9a00-11eb-8b02-22b0661762ee.png

**Debug Output**
Nothing specific.

**Comment by SteffeyDev** [comment]
Thanks for the write-up, I'll try to have this fixed for next release.

**Comment by SteffeyDev** [comment]
I found the issue, this will be fixed in next release (v4.0.0)

**Comment by SteffeyDev** [comment]
Fixed in 4.0.0

**Comment by SteffeyDev** [comment]
Re-open if it does not work for you
