### ISSUE TITLE
onCloseComplete dos not work on iOS

### ISSUE THREAD

**Issue by SikoraKam** [SteffeyDev/react-native-popover-view#98]
**Describe the bug**
On android everything is fine but on iOS prop onCloseComplete is not triggered. 
Try simple onRequestClose={() => console.log('isItWorking?')}

Additional, I am using isVisible and onRequestClose props if it change sth.

**Device/Setup Info:**
 - OS: iOS 14.3
 - `react-native` version: 0.63.4
- `react-native-popover-view` version: 3.1.1

**Comment by SteffeyDev** [comment]
Are you using expo? It's working in expo for me, but I don't have a non-expo app built to test in.

**Comment by SikoraKam** [comment]
no, I don't use expo

**Comment by SteffeyDev** [comment]
Ok, I think I have a fix ready for next release

**Comment by SteffeyDev** [comment]
This is actually a bug with `react-native` (https://github.com/facebook/react-native/issues/26892), but I found a work-around that bypasses the issue.

**Comment by SteffeyDev** [comment]
Fixed in 4.0.0
